# version: "3"
include:
  - ./docker-compose-configs.yml

services:
  tor:
    image: ${TOR_TAG}
    container_name: tor
    # Add bridges to torrc
    # https://bridges.torproject.org/options/
    configs:
      - source: tor_config
        target: /etc/tor/torrc
        mode: "0444"
    ports:
      - 9150:9150/tcp
      - 8853:8853/udp
    dns:
      - "${DNS_IP}"
    restart: unless-stopped
    labels:
      - "location=${LOCATION}"

  transmission:
    image: ${TRANSMISSION_TAG}
    container_name: transmission
    environment:
      - PUID=${WWW_USER_UID}
      - PGID=${WWW_USER_GID}
      - TZ=${TZ}
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_USER_PASS}
    volumes:
      - ${CONF_DIR}/transmission/config:/config
      - ${MEDIA_LIBARY}/transmission:/downloads
      - ${CONF_DIR}/transmission/watch:/watch
    ports:
      - 9091:9091/tcp
      - 51413:51413/tcp
      - 51413:51413/udp
    restart: unless-stopped
    labels:
      - "location=${LOCATION}"

  plex:
    image: ${PLEX_TAG}
    container_name: plex
    network_mode: host
    environment:
      - PLEX_UID=${WWW_USER_UID}
      - PLEX_GID=${WWW_USER_GID}
      - CHANGE_CONFIG_DIR_OWNERSHIP=false
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ALLOWED_NETWORKS=${PLEX_ALLOWED_NETWORKS}
    volumes:
      - ${CONF_DIR}/plex/database:/config
      - ${CONF_DIR}/plex/transcode:/transcode
      - ${MEDIA_LIBARY}:/data
    restart: unless-stopped
    labels:
      - "location=${LOCATION}"

  nginx:
    image: ${NGINX_TAG}
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/${DOMAIN}.conf
        mode: "0644"
    volumes:
      - ${CONF_DIR}/nginx/vhost.d:/etc/nginx/vhost.d:rw
      - ${CONF_DIR}/nginx/conf.d:/etc/nginx/conf.d:rw
      - ${CONF_DIR}/nginx/html:/usr/share/nginx/html:rw
      - ${CONF_DIR}/nginx/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
    labels:
      - "location=${LOCATION}"

  mysql:
    image: ${MYSQL_TAG}
    container_name: mysql
    volumes:
      - ${CONF_DIR}/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped
    labels:
      - "location=${LOCATION}"

  redis:
    image: ${REDIS_TAG}
    container_name: redis
    command: redis-server --appendonly yes --requirepass ${REDIS_HOST_PASSWORD}
    volumes:
      - ${CONF_DIR}/redis:/data
    restart: unless-stopped
    labels:
      - "location=${LOCATION}"

  letsencrypt:
    image: ${LETSENCRYPT_TAG}
    container_name: letsencrypt
    depends_on:
      - nginx
    volumes:
      - ${CONF_DIR}/nginx/vhost.d:/etc/nginx/vhost.d:rw
      - ${CONF_DIR}/nginx/conf.d:/etc/nginx/conf.d:rw
      - ${CONF_DIR}/nginx/html:/usr/share/nginx/html:rw
      - ${CONF_DIR}/nginx/certs:/etc/nginx/certs:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx
    restart: unless-stopped
    labels:
      - "location=${LOCATION}"

  nextcloud:
    image: ${NEXTCLOUD_TAG}
    container_name: nextcloud
    depends_on:
      - letsencrypt
      - nginx
      - mysql
      - redis
    volumes:
      - ${CONF_DIR}/nextcloud/html:/var/www/html
      - ${CONF_DIR}/nextcloud/config:/var/www/html/config
      - ${CONF_DIR}/nextcloud/custom_apps:/var/www/html/custom_apps
      - ${DATA_DIR}/nextcloud:/var/www/html/data
      - ${MEDIA_LIBARY}:/var/www/html/data/media_libary
      - ${CONF_DIR}/nextcloud/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    configs:
      - source: nexcloud_init
        target: /docker-entrypoint-hooks.d/pre-installation/init.sh
        uid: ${WWW_USER_UID}
        gid: ${WWW_USER_GID}
        mode: "0740"

    environment:
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      - NEXTCLOUD_TRUSTED_DOMAINS="${DOMAIN}"
      # - OVERWRITEHOST="${DOMAIN}"
      # - OVERWRITEPROTOCOL="https"
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}
      - APACHE_BODY_LIMIT=0
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
      - MYSQL_HOST=mysql
    restart: unless-stopped
    labels:
      - "location=${LOCATION}"

  # ON HOST ADD to cron
  # Nextcloud cron.php job
  # */5  *  *  *  * docker exec -t -u www-data nextcloud php -f cron.php

  prometheus:
    image: ${PROMETHEUS_TAG}
    container_name: prometheus
    user: ${WWW_USER}
    # user: root
    configs:
      - source: prom_config
        target: /etc/prometheus/prometheus.yml
      - source: prom_alerts
        target: /etc/prometheus/alerts.yml
    volumes:
#      - ${CONF_DIR}/prometheus:/etc/prometheus
      - ${DATA_DIR}/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.external-url=http://${IP}:9090"
      - "--web.enable-admin-api"
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
      - node-exporter:node-exporter
      - pushgateway:pushgateway
    restart: unless-stopped
    labels:
      - "location=${LOCATION}"
  pushgateway:
    image: ${PUSHGATEWAY_TAG}
    container_name: pushgateway
    restart: unless-stopped
    ports:
      - 9101:9091
    labels:
      - "location=${LOCATION}"

  node-cert-exporter:
    image: ${NODE_CERT_EXPORTER_TAG}
    container_name: node-cert-exporter
    volumes:
      - ${CONF_DIR}/nginx/certs:/etc/ssl:ro
    command:
      - "--path=/etc/ssl/${DOMAIN}/"
      - "--logtostderr=true"
    ports:
      - 9117:9117
    restart: unless-stopped
    labels:
      - "location=${LOCATION}"

  node-exporter:
    image: ${NODE_EXPORTER_TAG}
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      # - /:/rootfs:ro
      - /:/host:ro,rslave
    command:
      - "--path.rootfs=/host"
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc|run/udev/data)($$|/)"
      # - '--collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$'
    ports:
      - 9100:9100
    restart: unless-stopped
    labels:
      - "location=${LOCATION}"

  cadvisor:
    image: ${CADVISOR_TAG}
    container_name: cadvisor
    privileged: true
    volumes:
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /sys:/sys:ro
      - /var/run:/var/run:rw
      - /:/rootfs:ro
      - /sys/fs/cgroup:/cgroup:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - "-docker_only=true"
      - "-disable_metrics=percpu,sched,tcp,udp,disk,diskIO,accelerator,hugetlb,referenced_memory,cpu_topology,resctrl"
      - "-housekeeping_interval=30s"
    devices:
      - /dev/kmsg:/dev/kmsg
    restart: unless-stopped
    labels:
      - "location=${LOCATION}"

  alertmanager:
    image: ${ALERTMANAGER_TAG}
    container_name: alertmanager
    ports:
      - 9093:9093
    configs:
      - source: alertmanager_config
        target: /etc/alertmanager/config.yml
      - source: alertmanager_template
        target: /etc/alertmanager/templates/${DOMAIN}.tmpl
#    volumes:
#      - ${CONF_DIR}/alertmanager/:/etc/alertmanager/
    restart: unless-stopped
    links:
      - tor:tor
    environment:
      - "HTTPS_PROXY=socks5h://tor:9150"
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
      - "--web.external-url=http://${IP}:9093"
      # - '--log.level=debug'
    labels:
      - "location=${LOCATION}"

#  byedpi:
#    image: ${BYDPI_TAG}
#    container_name: byedpi
#    volumes:
#      - ${CONF_DIR}/byedpi/host.crack:/host.crack
#    # command: --hosts /host.crack -s1 -q1 -Y -Ar -s5 -o1+s -At -f-1 -r1+s -As -s1 -o1 +s -s-1 -An -b+500 --debug 1
#    command: --hosts /host.crack -s1 -q1 -Y -Ar -s5 -o25000+s -At -f-1 -r1+s -As -s1 -o1+s -s-1 -An -b+500 --debug 1
#    ports:
#      -  1080:1080
#        #    dns:
#        #      - "8.8.8.8"
#    restart: unless-stopped
#    labels:
#      - "location=${LOCATION}"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400

#configs:
#  alertmanager_config:
#    content: |
#      global:
#        telegram_api_url: "https://api.telegram.org"
#      
#      templates:
#        - '/etc/alertmanager/templates/*.tmpl'
#      
#      route:
#        group_by:
#          - 'alertname'
#      
#        group_wait: 30s
#        group_interval: 1m
#        repeat_interval: 3h
#        receiver: "black-hole"
#        routes:
#        - matchers:
#          - severity =~ "warning|critical"
#          receiver: "telegram"
#      receivers:
#        - name: "black-hole"
#        - name: "telegram"
#          telegram_configs:
#          - api_url: "https://api.telegram.org"
#            send_resolved: true
#            disable_notifications: false
#            bot_token: '${TELEGRAM_TOKEN}'
#            chat_id: ${TELEGRAM_CHAT}
#            parse_mode: "HTML"
#            message: '{{ template "telegram.srv.message" . }}'
#  alertmanager_template:
#    content: |
#      {{ define "tg-wide" }}{{ range . }}Labels:
#          {{ range .Labels.SortedPairs }}{{ .Name | toUpper }}: <b>{{ .Value }}</b>{{ end }}
#      Annotations:
#          {{ range .Annotations.SortedPairs }}{{ .Name | toUpper }}: {{ .Value }}{{ end }}
#      Source: {{ .GeneratorURL }}
#      {{ end }}
#      {{ end }}
#      
#      {{ define "tg" }}{{ range . }}
#      {{ .Annotations.description }}{{ .Name | toUpper }}: {{ .Value }}{{ end }}
#      {{ end }}
#      
#      {{ define "telegram.srv.message" }}
#      {{ if gt (len .Alerts.Firing) 0 }}
#      &#x1F525 Status: <b>{{ .Status | toUpper }}</b>
#      {{ template "tg" .Alerts.Firing }}
#      {{ end }}
#      {{ if gt (len .Alerts.Resolved) 0 -}}
#      &#x2705 Status: <b>{{ .Status | toUpper }} </b>
#      {{ template "tg" .Alerts.Resolved }}
#      {{ end }}
#      {{ end }}
#  nexcloud_init:
#    content: |
#      chown -R ${WWW_USER_UID}:${WWW_USER_GID} "/var/www/html/data"
#      echo "# Nextcloud data directory" > /var/www/html/data/.ncdata
#      chown ${WWW_USER_UID}:${WWW_USER_GID} /var/www/html/data/.ncdata
#  nginx_config:
#    content: |
#      upstream example.net {
#              server nextcloud:80;
#      }
#      server {
#              server_name example.net;
#              listen 80 ;
#              access_log /var/log/nginx/access.log vhost;
#              # include /etc/nginx/vhost.d/default;
#      }
#      server {
#              resolver 127.0.0.11;
#              server_name example.net;
#              listen 443 ssl;
#              http2  on;
#              # proxy_set_header Host $host;
#              access_log /var/log/nginx/access.log vhost;
#              ssl_session_timeout 5m;
#              ssl_session_cache shared:SSL:50m;
#              ssl_session_tickets off;
#              ssl_certificate /etc/nginx/certs/example.net.crt;
#              ssl_certificate_key /etc/nginx/certs/example.net.key;
#              ssl_dhparam /etc/nginx/certs/example.net.dhparam.pem;
#              ssl_stapling on;
#              ssl_stapling_verify on;
#              ssl_trusted_certificate /etc/nginx/certs/example.net.chain.pem;
#              add_header Strict-Transport-Security "max-age=31536000" always;
#              # include /etc/nginx/vhost.d/default;
#              client_max_body_size 10000M;
#              location / {
#                      proxy_pass http://example.net;
#              }
#              disable_symlinks off;
#      }
#  tor_config:
#    content: |
#      HardwareAccel 1
#      Log notice stdout
#      DNSPort 0.0.0.0:8853
#      SocksPort 0.0.0.0:9150
#      DataDirectory /var/lib/tor
#      UseBridges 1
#      # UpdateBridgesFromAuthority 1
#      # Install obfs4proxy (lyrebird) to container
#      # apk update & apk add obfs4proxy
#      ClientTransportPlugin obfs4 exec /usr/bin/lyrebird
#      # https://torscan-ru.ntc.party/
#      # sed 's/^obfs5 /Bridge obfs4 /g' -i /opt/tor/torrc
#      ${TOR_BRIDGES}
#  prom_alerts:
#    content: |
#      groups:
#      - name: host
#        rules:
#      
#        - alert: high_cpu_load
#          expr: node_load1 > 1.5
#          for: 30s
#          labels:
#            severity: warning
#          annotations:
#            summary: "Server under high load"
#            description: "Docker host is under high load, the avg load 1m is at {{ $$value }}. Reported by instance {{ $$labels.instance }} of job {{ $$labels.job }}."
#      
#        - alert: high_memory_load
#          expr: (sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100 > 85
#          for: 30s
#          labels:
#            severity: warning
#          annotations:
#            summary: "Server memory is almost full"
#            description: "Docker host memory usage is {{ humanize $$value }}%. Reported by instance {{ $$labels.instance }} of job {{ $$labels.job }}."
#      
#        - alert: high_storage_load_data
#          expr: (node_filesystem_size_bytes{mountpoint="/data"} - node_filesystem_free_bytes{mountpoint="/data"}) / node_filesystem_size_bytes{mountpoint="/data"}  * 100 > 85
#          for: 30s
#          labels:
#            severity: warning
#          annotations:
#            summary: "Server storage is almost full"
#            description: "Server storage usage is {{ humanize $$value }}%. Reported by instance {{ $$labels.instance }} of job {{ $$labels.job }}."
#      
#        - alert: full_storage_load_data
#          expr: (node_filesystem_size_bytes{mountpoint="/data"} - node_filesystem_free_bytes{mountpoint="/data"}) / node_filesystem_size_bytes{mountpoint="/data"}  * 100 == 100
#          for: 30s
#          labels:
#            severity: critical
#          annotations:
#            summary: "Server storage is full"
#            description: "Server storage usage is {{ humanize $$value }}%. Reported by instance {{ $$labels.instance }} of job {{ $$labels.job }}."
#      
#        - alert: high_storage_load_root
#          expr: (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"}  * 100 > 85
#          for: 30s
#          labels:
#            severity: warning
#          annotations:
#            summary: "Server storage is almost full"
#            description: "Server storage usage is {{ humanize $$value }}%. Reported by instance {{ $$labels.instance }} of job {{ $$labels.job }}."
#      
#        - alert: full_storage_load_root
#          expr: (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"}  * 100 == 100
#          for: 30s
#          labels:
#            severity: critical
#          annotations:
#            summary: "Server storage is full"
#            description: "Server storage usage is {{ humanize $$value }}%. Reported by instance {{ $$labels.instance }} of job {{ $$labels.job }}."
#      
#        - alert: TargetDown
#          expr: up == 0
#          for: 1m
#          labels:
#            severity: critical
#          annotations:
#            summary: "Target {{ $$labels.instance }} down"
#            description: "{{ $$labels.instance }} of job {{ $$labels.job }} has been down for more than 1 minute."
#      
#        - alert: RaidStateWarn
#          expr: node_md_disks{device=~"md[0-9]{3}",state!="active"} > 0
#          for: 0m
#          labels:
#            severity: critical
#          annotations:
#            summary: Host RAID array got not active
#            description: "RAID array {{ $$labels.device }} is in degraded state due to one or more disks failures."
#      
#      - name: certificates
#        rules:
#      
#        - alert: certificate_expiration_warning
#          expr: round(ssl_certificate_expiry_seconds / 60 / 60 / 24, 1) < 20
#          for: 1m
#          labels:
#            severity: warning
#          annotations:
#            summary: Your certificate will expire in 20 days
#            description: "Your certificate for <b>{{ $$labels.dns_names }}</b> will expire in 20 days "
#      
#        - alert: certificate_expiration
#          expr: round(ssl_certificate_expiry_seconds / 60 / 60 / 24, 1) < 1
#          for: 1m
#          labels:
#            severity: critical
#          annotations:
#            summary: Your certificate is expired
#            description: "Your certificate for <b>{{ $$labels.dns_names }}</b> is expired"
#      
#      - name: docker
#        rules:
#      
#        - alert: ContainerDown_alertmanager
#          expr: absent(container_memory_usage_bytes{name="alertmanager"})
#          for: 1m
#          labels:
#            severity: warning
#          annotations:
#            summary: "Container <b>alertmanager</b> down"
#            description: "Container <b>alertmanager</b> has been down for more than 1 minute."
#      
#        - alert: ContainerDown_cadvisor
#          expr: absent(container_memory_usage_bytes{name="cadvisor"})
#          for: 1m
#          labels:
#            severity: warning
#          annotations:
#            summary: "Container <b>cadvisor</b> down"
#            description: "Container <b>cadvisor</b> has been down for more than 1 minute."
#      
#              #  - alert: ContainerDown_dns
#              #    expr: absent(container_memory_usage_bytes{name="dns"})
#              #    for: 1m
#              #    labels:
#              #      severity: critical
#              #    annotations:
#              #      summary: "Container <b>dns</b> down"
#              #      description: "Container <b>dns</b> has been down for more than 1 minute."
#      
#        - alert: ContainerDown_letsencrypt
#          expr: absent(container_memory_usage_bytes{name="letsencrypt"})
#          for: 1m
#          labels:
#            severity: warning
#          annotations:
#            summary: "Container <b>letsencrypt</b> down"
#            description: "Container <b>letsencrypt</b> has been down for more than 1 minute."
#      
#        - alert: ContainerDown_mysql
#          expr: absent(container_memory_usage_bytes{name="mysql"})
#          for: 1m
#          labels:
#            severity: critical
#          annotations:
#            summary: "Container <b>mysql</b> down"
#            description: "Container <b>mysql</b> has been down for more than 1 minute."
#      
#        - alert: ContainerDown_nextcloud
#          expr: absent(container_memory_usage_bytes{name="nextcloud"})
#          for: 1m
#          labels:
#            severity: critical
#          annotations:
#            summary: "Container <b>nextcloud</b> down"
#            description: "Container <b>nextcloud</b> has been down for more than 1 minute."
#      
#        - alert: ContainerDown_nginx_proxy
#          expr: absent(container_memory_usage_bytes{name="nginx"})
#          for: 1m
#          labels:
#            severity: critical
#          annotations:
#            summary: "Container <b>nginx</b> down"
#            description: "Container <b>nginx</b> has been down for more than 1 minute."
#      
#        - alert: ContainerDown_node-exporter
#          expr: absent(container_memory_usage_bytes{name="node-exporter"})
#          for: 1m
#          labels:
#            severity: warning
#          annotations:
#            summary: "Container <b>node-exporter</b> down"
#            description: "Container <b>node-exporter</b> has been down for more than 1 minute."
#      
#        - alert: ContainerDown_plex
#          expr: absent(container_memory_usage_bytes{name="plex"})
#          for: 1m
#          labels:
#            severity: critical
#          annotations:
#            summary: "Container <b>plex</b> down"
#            description: "Container <b>plex</b> has been down for more than 1 minute."
#      
#        - alert: ContainerDown_redis
#          expr: absent(container_memory_usage_bytes{name="redis"})
#          for: 1m
#          labels:
#            severity: warning
#          annotations:
#            summary: "Container <b>redis</b> down"
#            description: "Container <b>redis</b> has been down for more than 1 minute."
#      
#        - alert: ContainerDown_transmission
#          expr: absent(container_memory_usage_bytes{name="transmission"})
#          for: 1m
#          labels:
#            severity: critical
#          annotations:
#            summary: "Container <b>transmission</b> down"
#            description: "Container <b>transmission</b> has been down for more than 1 minute."
#      
#        - alert: ContainerDown_prometheus
#          expr: absent(container_memory_usage_bytes{name="prometheus"})
#          for: 1m
#          labels:
#            severity: warning
#          annotations:
#            summary: "Container <b>prometheus</b> down"
#            description: "Container <b>prometheus</b> has been down for more than 1 minute."
#      
#      - name: backup
#        rules:
#        - alert: Backup_Status_False
#          expr: backup_status == 0
#          for: 0m
#          labels:
#            severity: critical
#          annotations:
#            summary: "Backup <b>{{ $$labels.exported_instance }}</b> failed"
#            description: "Backup on <b>{{ $$labels.exported_instance }}</b> is failed"
#        
#  prom_config:
#    content: |
#      global:
#        scrape_interval: 1m
#        scrape_timeout: 1m
#      
#      alerting:
#        alertmanagers:
#          - static_configs:
#              - targets:
#                  - "alertmanager:9093"
#      rule_files:
#        - "alerts.yml"
#      
#      scrape_configs:
#        - job_name: "prometheus"
#          static_configs:
#          - targets: ["localhost:9090"]
#      
#        - job_name: "pushgateway"
#          metrics_path: /metrics
#          scheme: http
#          static_configs:
#          - targets: ["pushgateway:9091"]
#      
#        - job_name: "node"
#          enable_http2: false
#          tls_config:
#            insecure_skip_verify: true
#          static_configs:
#          - targets: ["node-exporter:9100"]
#      
#        - job_name: "node-cert"
#          enable_http2: false
#          tls_config:
#            insecure_skip_verify: true
#          static_configs:
#          - targets: ["node-cert-exporter:9117"]
#      
#        - job_name: "docker"
#          static_configs:
#          - targets: ["172.17.0.1:9323"]
#      
#        - job_name: 'cadvisor'
#          static_configs:
#            - targets: ['cadvisor:8080']
#
